### ISSUE TITLE
Possible certificate issue with machine-api-provider-nutanix

### ISSUE THREAD

**Issue by tonyjames** [openshift/machine-api-provider-nutanix#21]
Environment:

Prism Central 2022.4.0.2
AOS 5.20.4.6
OpenShift 4.11.0-rc.6

I'm able to provision an OpenShift cluster only if I mark the masters as schedulable. If the masters are not  schedulable the install process fails because the worker VMs are never created. The issue seems to be with the machine api controller. My Prism Central and Prism Element instances are both using certificates that were issued by my CA. I've added my CA certificate to the install-config.yaml in the `additionalTrustBundle` section but the machine-api-controllers pod is still showing errors like this:

```
E0804 13:18:31.658277       1 controller.go:289] ocp-sb6wr-worker-x4msc: failed to check if machine exists: Error when finding VM by name ocp-sb6wr-worker-x4msc. error: Post "https://prism.tonyjames.lab:9440/api/nutanix/v3/vms/list": x509: certificate signed by unknown authority
```

**Comment by tonyjames** [comment]
I just tested with the GA bits for OpenShift 4.11.0 and the issue is still present.

**Comment by thunderboltsid** [comment]
@tonyjames Thanks for creating the issue. In the case of a Prism cluster with self-signed certificates, you need to modify the proxy spec in the cluster proxy manifest to specify the user-provided CA bundle is a trusted CA.

in `manifests/cluster-proxy-01-config.yaml`
```yaml
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  creationTimestamp: null
  name: cluster
spec:
  trustedCA:
    name: "user-ca-bundle"
```

**Comment by tonyjames** [comment]
Thanks @thunderboltsid, that seems to have resolved the issue. Would it be possible to have this step added to the documentation for installing OpenShift 4.11 on Nutanix? I don't recall having to manually update the cluster-proxy manifest for other IPI deployment targets.

**Comment by thunderboltsid** [comment]
> Thanks @thunderboltsid, that seems to have resolved the issue. Would it be possible to have this step added to the documentation for installing OpenShift 4.11 on Nutanix? I don't recall having to manually update the cluster-proxy manifest for other IPI deployment targets.

Looking at the other providers, it seems the other providers are basically taking the cert from the configmap and tacking it on to the tls trust bundle. We can also do the same for Nutanix MAPI provider; that way modifying the cluster proxy won't be needed.

**Comment by tonyjames** [comment]
> @vnephologist in the meanwhile, let's make sure our documentation reflects the extra step of modifying the cluster proxy in the case of self-signed certs.

One point, I'm not using self-signed certificates. I run my own CA and simply adding the CA certificate to the `additionalTrustBundle` was not enough for a successful IPI install.

**Comment by vnephologist** [comment]
@tonyjames I’ll update the doc at OpenDocs.Nutanix.com (unless you beat me to it) but just to clarify, your root CA is not signed itself by a known public trusted authority, correct?

**Comment by tonyjames** [comment]
That is correct. I guess "technically" that makes it a self-signed CA :)

**Comment by vnephologist** [comment]
Updated doc here: https://opendocs.nutanix.com/openshift/install/ipi/

**Comment by pipoe2h** [comment]
I've been scratching my head for a while with this until I saw that despite having the internal CA in the `install-config.yaml`, it was also required in the proxy file even if a proxy is not used. Any plan for automatically updating the `manifests/cluster-proxy-01-config.yaml` if `additionalTrustBundle` exists in `install-config.yaml`?

**Comment by pipoe2h** [comment]
Update, even including the cert info in proxy file, it's still failing.

```nutanix@App45046d83-5:~$ oc get clusteroperators
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.11.3    False       False         True       45m     OAuthServerServiceEndpointAccessibleControllerAvailable: Get "https://172.30.189.133:443/healthz": dial tcp 172.30.189.133:443: i/o timeout (Client.Timeout exceeded while awaiting headers)...
baremetal                                  4.11.3    True        False         False      44m     
cloud-controller-manager                   4.11.3    True        False         False      46m     
cloud-credential                           4.11.3    True        False         False      43m     
cluster-autoscaler                         4.11.3    True        False         False      44m     
config-operator                            4.11.3    True        False         False      45m     
console                                    4.11.3    False       False         True       28m     RouteHealthAvailable: console route is not admitted
csi-snapshot-controller                    4.11.3    True        False         False      44m     
dns                                        4.11.3    True        False         False      44m     
etcd                                       4.11.3    True        False         False      43m     
image-registry                             4.11.3    True        False         False      32m     
ingress                                              False       True          True       44m     The "default" ingress controller reports Available=False: IngressControllerUnavailable: One or more status conditions indicate unavailable: DeploymentAvailable=False (DeploymentUnavailable: The deployment has Available status condition set to False (reason: MinimumReplicasUnavailable) with message: Deployment does not have minimum availability.)
insights                                   4.11.3    True        False         False      30m     
kube-apiserver                             4.11.3    True        False         False      40m     
kube-controller-manager                    4.11.3    True        False         False      42m     
kube-scheduler                             4.11.3    True        False         False      41m     
kube-storage-version-migrator              4.11.3    True        False         False      45m     
machine-api                                4.11.3    True        False         False      41m     
machine-approver                           4.11.3    True        False         False      44m     
machine-config                             4.11.3    True        False         False      43m     
marketplace                                4.11.3    True        False         False      44m     
monitoring                                           False       True          True       30m     Rollout of the monitoring stack failed and is degraded. Please investigate the degraded status error.
network                                    4.11.3    True        True          False      45m     Deployment "/openshift-network-diagnostics/network-check-source" is waiting for other operators to become ready
node-tuning                                4.11.3    True        False         False      44m     
openshift-apiserver                        4.11.3    True        False         False      33m     
openshift-controller-manager               4.11.3    True        False         False      40m     
openshift-samples                          4.11.3    True        False         False      35m     
operator-lifecycle-manager                 4.11.3    True        False         False      44m     
operator-lifecycle-manager-catalog         4.11.3    True        False         False      44m     
operator-lifecycle-manager-packageserver   4.11.3    True        False         False      36m     
service-ca                                 4.11.3    True        False         False      45m     
storage                                    4.11.3    True        False         False      45m

**Comment by tonyjames** [comment]
@pipoe2h if you look at the logs for the machine-api-controllers pod do you still see the same x509 errors?

**Comment by pipoe2h** [comment]
@tonyjames no, it's not a certificate issue. I've made progress, downgrading to 4.11.1 or 4.11.2 works. It seems to be a regression issue with 4.11.3 (stable), I'm going to try with 4.11.4 & 4.11.5 to see if the issue persists.

**Comment by vnephologist** [comment]
@thunderboltsid are you aware of any changes between the above releases?

**Comment by thunderboltsid** [comment]
Interesting, no changes in cert handling on our side; taking a look.

**Comment by pipoe2h** [comment]
Apologies all, false alarm, 4.11.3 also works. Found the issue from my side. It was related to the `machineNetwork` value in the `install-config.yaml`. My understanding was that the value should match the actual subnet where virtual machines are deployed, and that's not the case. If my understanding was right, should we add any additional detail to mention that also this network must not overlap with the AHV subnet for virtual machines?

**Comment by yanhua121** [comment]
In OCP 4.12, the installer adds the below new field to the install-config.yaml.

additionalTrustBundlePolicy:
            description: 'AdditionalTrustBundlePolicy determines when to add the AdditionalTrustBundle
              to the nodes'' trusted certificate store. "Proxyonly" is the default.
              The field can be set to following specified values. "Proxyonly" : adds
              the AdditionalTrustBundle to nodes when http/https proxy is configured.
              "Always" : always adds AdditionalTrustBundle.'

When the PC credentials is self-signed, users need to add the below two fields to the install-config.yaml file:
additionalTrustBundle: <self-signed CA>
additionalTrustBundlePolicy: "Always"

Then the 4.12 installer will generate the manifests/user-ca-bundle-config.yaml with the <self-signed CA> data, and also will generate the manifests/cluster-proxy-01-config.yaml as below.

apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  creationTimestamp: null
  name: cluster
spec:
  trustedCA:
    name: user-ca-bundle
status: {}

Since "additionalTrustBundlePolicy" is the new field of InstallConfig, I think OpenShift team will document on how to use it and what use cases it is used in the OCP 4.12 document. The use cases include the self-signed certificate issue we discuss here.

---------------------
@thunderboltsid @vnephologist @pipoe2h @tonyjames

**Comment by thunderboltsid** [comment]
We will work towards supporting user provided certs natively in Nutanix machine API provider.
