### ISSUE TITLE
Support sysprep guest_customization 

### ISSUE THREAD

**Issue by aravindhp** [openshift/machine-api-provider-nutanix#30]
Nutanix Prism Central v3 [vms](https://www.nutanix.dev/api_references/prism-central-v3/#/8ed04dbbc5818-create-a-new-vm) API provides an option for specifying `sysprep` `guest_customization` for Windows VMs. 

```
sysprep
object

If this field is set, the guest will be customized using Sysprep. Either unattend_xml or custom_key_values should be provided. If custom_key_values are provided then the unattended answer file will be generated using these key-value pairs.
install_type
string

Whether the guest will be freshly installed using this unattend configuration, or whether this unattend configuration will be applied to a pre-prepared image. Default is "PREPARED".
Default:
PREPARED
unattend_xml
string

This field contains a Sysprep unattend xml definition, as a string. The value must be base64 encoded.
<= 32000 characters
custom_key_values
Generic key value pair

Generic key value pair used for custom attributes
```

Add support for specifying the above in the Machine spec. The XML will be specified in the user-data section in the Machine spec.

**Comment by vnephologist** [comment]
Thanks for getting to the bottom of this @aravindhp. @yanhua121, I'll file a tracker.

**Comment by wolfganghuse** [comment]
This can be closed as we can use cloudbase-init to parse userdata from cloud-init. So we don´t need to sysprep the whole image and can just inject powershell-scripts as example.

**Comment by yanhua121** [comment]
@vnephologist Can you close this issue, as @wolfganghuse indicated above, we do not need to do anything of sysprep, when creating the worker VM for Windows.
