### ISSUE TITLE
support DHCP for network config of controlplane and workers

### ISSUE THREAD

**Issue by wolfganghuse** [openshift/machine-api-provider-nutanix#31]
When using DHCP instead of IPAM the Hostname of the VM is not set by DHCP. In these case we need to inject the desired hostname through cloud-init for both control-plane and worker nodes.
A script running on the worker can check hostname and set it based on temporary file if needed (silimiar to VMware implementation).
As alternative we could set /etc/hostname directly, but we must evaluate if this impacts other ways of configuring the hostname.

A suitable cloud-init extra argument could look like this:
`write_files:
- content: |
    myhostname
  path: /tmp/hostname`

**Comment by yanhua121** [comment]
Created https://jira.nutanix.com/browse/KRBN-6008 to track.

**Comment by yanhua121** [comment]
Related RH slack discussion: https://coreos.slack.com/archives/C0211848DBN/p1666968673015319
