### ISSUE TITLE
Support multiple PE in openshift-install

### ISSUE THREAD

**Issue by wolfganghuse** [openshift/machine-api-provider-nutanix#32]
Given: One PrismCentral with multiple Clusters

openshift-install should be able to do multi-cluster installations.

- Install Worker-Nodes in different Cluster than ControlPlane
- Distribute Controlplane across three Clusters

**Comment by yanhua121** [comment]
Created https://jira.nutanix.com/browse/KRBN-6109 for this and targeted it to OCP-4.13.
